import { createContext, useContext, useState } from 'react'

const LangContext = createContext()

export const translations = {
 en: {
 // Nav
 nav_home: 'Home',
 nav_about: 'About Us',
 nav_activities: 'Our Activities',
 nav_why: 'Why Us',
 nav_contact: 'Get in Touch',

 // Top banner
 banner_group: 'Hadakah Group',
 banner_sub: 'Al Khabbaz Corporate Enterprise',
 banner_location: 'Al-Khobar, Eastern Province, Saudi Arabia',
 banner_arabic: 'مجموعة حداقة للخدمات التجارية',

 // Home Hero
 hero_tag: 'Established in Al-Khobar, Saudi Arabia',
 hero_title_1: 'Business Excellence',
 hero_title_2: 'Across',
 hero_title_span: 'Four Pillars',
 hero_desc: 'Al Khabbaz Corporate Enterprise — serving businesses, factories, hospitals and government entities in Saudi Arabia with trading, advertising, calligraphy and printing services from our Al-Khobar headquarters.',
 hero_btn_activities: 'Explore Our Activities',
 hero_btn_contact: 'Contact Us',
 hero_stat_1_num: '4',
 hero_stat_1_lbl: 'Business Activities',
 hero_stat_2_num: '20+',
 hero_stat_2_lbl: 'Years Experience',
 hero_stat_3_num: 'KSA',
 hero_stat_3_lbl: 'Saudi Arabia',

 // Service mini cards
 svc_trading_title: 'Hadakah Trading',
 svc_trading_desc: 'General supplies, electronics, safety & office equipment',
 svc_advert_title: 'Advertising & Promotion',
 svc_advert_desc: 'Marketing campaigns, promotional design & media',
 svc_calli_title: 'Calligraphy & Signs',
 svc_calli_desc: 'Arabic calligraphy, signage & artistic lettering',
 svc_print_title: 'Hadakah Printing',
 svc_print_desc: 'Commercial offset & digital printing solutions',

 // Strip
 strip_1_title: 'Corporate Enterprise',
 strip_1_desc: 'Part of Al Khabbaz Corporate Enterprise, serving the Eastern Province',
 strip_2_title: 'Al-Khobar, KSA',
 strip_2_desc: 'EKDB2729, 2729 Al Awal Street, Al-Khobar Ash Shamaliya',
 strip_3_title: 'Online Presence',
 strip_3_desc: 'hadakah.com · alkhabbaz.net · hadakah-hpc.com.sa',
 strip_4_title: 'Reach Us',
 strip_4_desc: 'info@hadakah.com · info@alkhabbaz.net',

 // CTA
 cta_title: 'Ready to work with us?',
 cta_desc: 'Contact our team in Al-Khobar to discuss your requirements. We respond promptly and work to find the right solution for your business.',
 cta_enquiry: 'Send an Enquiry',
 cta_learn: 'Learn About Us',

 // About page
 page_about_tag: 'Our Story',
 page_about_title: 'About Hadakah Group',
 page_about_desc: 'Al Khabbaz Corporate Enterprise — built on trust, excellence and regional experience.',
 about_group_tag: 'About the Group',
 about_h2: 'Al Khabbaz Corporate Enterprise',
 about_p1: 'Hadakah Group operates as part of Al Khabbaz Corporate Enterprise (KCE), a business established in Al-Khobar, Eastern Province of Saudi Arabia. KCE\'s activities cover general service trading, IT & internet, engineering, operations & maintenance, and hygiene services.',
 about_p2: 'The Group\'s activities reflect the breadth of the Saudi market — from supplying electrical equipment and uniforms to factories and hospitals, to delivering advertising campaigns, Arabic calligraphy, and commercial printing across the Kingdom.',
 pillar_1: 'Reliable Delivery',
 pillar_2: 'Quality Assured',
 pillar_3: 'Local Expertise',
 pillar_4: 'Professional Team',
 about_years: 'Years Serving',
 about_activities: 'Activities',
 mission_title: 'Our Mission',
 mission_text: 'To serve businesses, factories, hospitals, and government entities in Saudi Arabia with reliable supply, professional services, and responsive support — built on long-term relationships with our clients.',
 vision_title: 'Our Vision',
 vision_text: 'To grow as the preferred multi-service group in the Eastern Province, known for quality, reliability, and deep understanding of the Saudi market.',
 entities_tag: 'Group Structure',
 entities_title: 'Our Business Entities',
 entity_1_name: 'Al Khabbaz Corporate Enterprise',
 entity_1_desc: 'The parent holding company overseeing all Hadakah Group activities and subsidiaries.',
 entity_2_name: 'Hadakah Trading Establishment',
 entity_2_desc: 'General trading, supplies, electronics, safety equipment and industrial materials.',
 entity_3_name: 'Hadakah Hygiene & Pest Control',
 entity_3_desc: 'Professional hygiene management and integrated pest control services.',
 entity_4_name: 'Al Khabbaz Engineering Consultant',
 entity_4_desc: 'Engineering consultancy, operations & maintenance, and technical advisory services.',

 // Activities page — titles match PDF exactly
 page_act_tag: 'What We Do',
 page_act_title: 'Our Four Core Activities',
 page_act_desc: 'From trading and advertising to calligraphy and printing — Hadakah Group delivers professional services across every dimension of your business needs.',
 act_1_label: 'Activity 1',
 act_1_title: 'Hadakah Trading',
 act_1_desc: 'General service trading across industrial, commercial, and office domains. We supply quality products to businesses, hospitals, factories, and government entities throughout the Kingdom.',
 act_1_items: ['Electrical equipment & electronics', 'Industrial safety equipment', 'Readymade uniforms & workwear', 'Computers, laptops & accessories', 'Photography & communication devices', 'General supplies for offices, factories & hospitals', 'Gifts & promotional items'],
 act_1_link: 'View product catalogue',
 act_2_label: 'Activity 2',
 act_2_title: 'Hadakah Advertising & Promotion',
 act_2_desc: 'Strategic advertising and promotional services designed to elevate your brand presence in the Saudi market. From campaign design to full media production, we make your message heard.',
 act_2_items: ['Brand design & visual identity', 'Advertising campaign creation', 'Promotional material design', 'Event marketing & signage', 'Digital & print media production', 'Corporate communications'],
 act_2_link: 'Explore advertising services',
 act_3_label: 'Activity 3',
 act_3_title: 'Hadakah Calligraphy & Signs',
 act_3_desc: 'Masterful Arabic calligraphy and professional signage services blending traditional artistry with modern commercial applications. Ideal for corporate branding, interiors, and public spaces.',
 act_3_items: ['Arabic calligraphy artwork', 'Corporate signage & wayfinding', 'Interior design lettering', 'Custom name plates & plaques', 'Artistic & decorative scripts', 'Monument & building signs'],
 act_3_link: 'See calligraphy portfolio',
 act_4_label: 'Activity 4',
 act_4_title: 'Hadakah Printing',
 act_4_desc: 'Commercial and digital printing services for businesses of all sizes. From small-format marketing materials to large-format displays, we deliver precision and quality every time.',
 act_4_items: ['Offset & digital printing', 'Business cards, brochures & flyers', 'Large-format banners & displays', 'Corporate stationery & forms', 'Packaging & label printing', 'Books & catalogues'],
 act_4_link: 'Request a print quote',

 // WhyUs page
 page_why_tag: 'Why Hadakah',
 page_why_title: 'Why Partner With Us',
 page_why_desc: 'We bring decades of regional expertise, a professional team, and a commitment to delivering results across all our business activities.',
 feat_1_title: 'Proven Track Record',
 feat_1_desc: 'Al Khabbaz Corporate Enterprise has been serving clients across the Eastern Province for over 20 years, building lasting relationships with companies, government bodies, and institutions throughout the Kingdom.',
 feat_2_title: 'Multi-Service Capability',
 feat_2_desc: 'From electrical equipment and safety gear to advertising campaigns and Arabic calligraphy — our group covers a wide range of commercial needs, so clients can rely on one trusted partner.',
 feat_3_title: 'Local Market Knowledge',
 feat_3_desc: 'Based in Al-Khobar, we understand the requirements, regulations, and business culture of the Saudi market — giving our clients a reliable local partner with real market knowledge.',
 feat_4_title: 'Responsive Service',
 feat_4_desc: 'Our team responds promptly to enquiries and orders. We understand that businesses need reliable timelines — and we work hard to deliver on them every time.',
 feat_5_title: 'Creative Excellence',
 feat_5_desc: 'Our calligraphy and advertising teams combine artistic mastery with commercial effectiveness — creating work that truly stands out.',
 feat_6_title: 'Trust & Integrity',
 feat_6_desc: 'We operate with full transparency and professionalism. Long-term relationships with our clients are the foundation of how we work.',
 val_tag: 'Our Values',
 val_title: 'What Drives Us',
 val_1_title: 'Quality',
 val_1_desc: 'Every product and service we deliver meets the highest standards of quality and professionalism.',
 val_2_title: 'Relationships',
 val_2_desc: 'We invest in long-term partnerships, treating every client as a valued collaborator.',
 val_3_title: 'Innovation',
 val_3_desc: 'From traditional calligraphy to modern digital printing, we blend heritage with contemporary practice.',
 val_4_title: 'Integrity',
 val_4_desc: 'Transparent communication, fair dealings, and a commitment to our word — always.',

 // Contact page
 page_contact_tag: 'Get in Touch',
 page_contact_title: 'Contact Hadakah Group',
 page_contact_desc: 'We welcome enquiries from businesses and partners. Reach us through any of the channels below.',
 contact_phone_label: 'Telephone',
 contact_phone_1: '+966 505-800546',
 contact_phone_2: '+966 581-592107',
 contact_phone_3: '+966 559-016710',
 contact_email_label: 'Email Addresses',
 contact_email_1: 'info@hadakah.com',
 contact_email_2: 'info@alkhabbaz.net',
 contact_email_3: 'hdadvertising@gmail.com',
 contact_web_label: 'Websites',
 contact_addr_title: 'Registered Address',
 contact_addr_code: 'EKDB2729',
 contact_addr_street: '2729 Al Awal Street',
 contact_addr_district: 'Al-Khobar Ash Shamaliya Dist., 34429-6366',
 contact_addr_city: 'Al-Khobar, Eastern Province',
 contact_addr_country: 'Kingdom of Saudi Arabia',
 form_title: 'Send Us an Enquiry',
 form_name: 'Full Name *',
 form_name_ph: 'Your full name',
 form_company: 'Company',
 form_company_ph: 'Your company name',
 form_email: 'Email Address *',
 form_email_ph: 'your@email.com',
 form_phone: 'Phone Number',
 form_phone_ph: '+966 ...',
 form_activity: 'Activity of Interest',
 form_act_default: '— Select an activity —',
 form_act_1: 'Hadakah Trading (Activity 1)',
 form_act_2: 'Hadakah Advertising & Promotion (Activity 2)',
 form_act_3: 'Hadakah Calligraphy & Signs (Activity 3)',
 form_act_4: 'Hadakah Printing (Activity 4)',
 form_act_5: 'General Enquiry',
 form_msg: 'Message *',
 form_msg_ph: 'Tell us about your requirements...',
 form_submit: 'Send Enquiry',
 form_note: 'We typically respond within 1–2 business days.',
 form_success_title: 'Thank you for your enquiry!',
 form_success_desc: 'We have received your message and will respond within 1–2 business days.',
 form_another: 'Send Another',

 // Footer
    // ── Detail pages ──
    trading_section_tag: 'Product Categories',
    trading_section_h2: 'What We Supply',
    trading_cta_h2: 'Request a Trading Quote',
    trading_cta_p: 'Tell us what you need and we will source it promptly.',
    t_elec_title: 'Electrical & Electronics',
    t_elec_desc: 'Industrial electrical equipment, electronic devices, cables, switchgear, and communication hardware.',
    t_safety_title: 'Industrial Safety Equipment',
    t_safety_desc: 'PPE, hard hats, safety vests, fire protection gear, and safety signage for factories and facilities.',
    t_uniform_title: 'Readymade Uniforms & Workwear',
    t_uniform_desc: 'Corporate uniforms, industrial workwear, T-shirts, reflective vests, and custom branded clothing.',
    t_laptop_title: 'Computers, Laptops & Accessories',
    t_laptop_desc: 'Desktops, laptops, printers, peripherals, networking equipment, and photography devices.',
    t_gifts_title: 'Gifts & Promotional Items',
    t_gifts_desc: 'Corporate gifts, branded merchandise, promotional giveaways, and customised items for events.',
    t_supply_title: 'General Office & Industrial Supplies',
    t_supply_desc: 'Complete supply solutions for offices, hospitals, factories, and government entities.',
    adv_section_tag: 'Our Services',
    adv_section_h2: 'Advertising & Promotion Services',
    adv_cta_h2: 'Start Your Advertising Campaign',
    adv_cta_p: 'Tell us about your brand and goals and we will craft a strategy that gets results.',
    a_brand_title: 'Brand Design & Visual Identity',
    a_brand_desc: 'Logo design, colour palettes, typography, brand guidelines, and full visual identity packages.',
    a_campaign_title: 'Advertising Campaign Creation',
    a_campaign_desc: 'End-to-end campaign strategy, creative concept, copywriting in Arabic and English, and media placement.',
    a_promo_title: 'Promotional Material Design',
    a_promo_desc: 'Brochures, flyers, posters, roll-ups, and all marketing collateral — designed and printed on demand.',
    a_event_title: 'Event Marketing & Signage',
    a_event_desc: 'Event branding, stage backdrops, exhibition stands, and full event visual packages.',
    a_digital_title: 'Digital & Print Media Production',
    a_digital_desc: 'Social media graphics, digital ads, email campaigns, and coordinated print-digital campaigns.',
    a_corp_title: 'Corporate Communications',
    a_corp_desc: 'Annual reports, company profiles, presentation decks, and all branded corporate documents.',
    cal_section_tag: 'Our Services',
    cal_section_h2: 'Calligraphy & Signs Services',
    cal_cta_h2: 'Commission Custom Calligraphy',
    cal_cta_p: 'Share your vision and our artists will bring it to life in Arabic or English.',
    c_calli_title: 'Arabic Calligraphy Artwork',
    c_calli_desc: 'Traditional and modern Arabic calligraphy for corporate use, gifts, wall installations, and cultural displays.',
    c_signs_title: 'Corporate Signage & Wayfinding',
    c_signs_desc: 'Professional exterior and interior signage systems, directional signs, and complete wayfinding solutions.',
    c_interior_title: 'Interior Design Lettering',
    c_interior_desc: 'Bespoke wall lettering, inspirational quotes, and decorative typography for corporate interiors.',
    c_plaques_title: 'Custom Name Plates & Plaques',
    c_plaques_desc: 'Engraved and printed name plates, award plaques, and recognition displays.',
    c_deco_title: 'Artistic & Decorative Scripts',
    c_deco_desc: 'Ornamental Arabic scripts, Islamic geometric art, and artistic commissions for hotels and mosques.',
    c_monument_title: 'Monument & Building Signs',
    c_monument_desc: 'Large-scale exterior monument signs, building identification, and architectural lettering.',
    print_section_tag: 'Print Services',
    print_section_h2: 'Printing Solutions',
    print_quote_tag: 'Get a Price',
    print_quote_h2: 'Request a Print Quote',
    print_quote_p: 'Fill in the details below and we will send you a competitive quote within 24 hours.',
    print_request_btn: 'Request a Quote',
    print_success_h3: 'Quote Request Received!',
    print_success_p: 'Thank you — we will send your print quote within 24 hours.',
    print_submit_btn: 'Submit Quote Request',
    print_qty_ph: 'e.g. 500, 1000, 5000',
    print_notes_ph: 'Size, paper type, finishing, artwork ready? Any special requirements...',
    print_type_lbl: 'Print Type *',
    print_qty_lbl: 'Quantity',
    print_notes_lbl: 'Additional Notes',
    print_opt_default: '— Select type —',
    print_opt_1: 'Business Cards',
    print_opt_2: 'Brochures / Flyers',
    print_opt_3: 'Banners & Displays',
    print_opt_4: 'Corporate Stationery',
    print_opt_5: 'Packaging & Labels',
    print_opt_6: 'Books & Catalogues',
    print_opt_7: 'Other',
    p_offset_title: 'Offset & Digital Printing',
    p_offset_desc: 'High-volume commercial offset printing and short-run digital printing with exceptional colour accuracy.',
    p_cards_title: 'Business Cards, Brochures & Flyers',
    p_cards_desc: 'Premium business cards, tri-fold brochures, A5/A4 flyers, and all small-format marketing materials.',
    p_banner_title: 'Large-Format Banners & Displays',
    p_banner_desc: 'Roll-up banners, vinyl banners, outdoor hoarding, exhibition displays, and building wraps.',
    p_stationary_title: 'Corporate Stationery & Forms',
    p_stationary_desc: 'Letterheads, envelopes, invoice forms, order pads, delivery notes, and complete stationery packages.',
    p_packaging_title: 'Packaging & Label Printing',
    p_packaging_desc: 'Product labels, carton printing, sticker rolls, and custom packaging boxes.',
    p_books_title: 'Books, Catalogues & Magazines',
    p_books_desc: 'Perfect-bound books, saddle-stitch catalogues, annual reports, and full magazine production.',

 footer_desc: 'A trusted multi-service corporate enterprise headquartered in Al-Khobar, Saudi Arabia — delivering excellence across trading, advertising, calligraphy, and printing.',
 footer_quick: 'Quick Links',
 footer_activities: 'Activities',
 footer_contact: 'Contact',
 footer_copyright: '© 2025 Al Khabbaz Corporate Enterprise / Hadakah Group. All rights reserved. · Al-Khobar, Eastern Province, Kingdom of Saudi Arabia.',
 },

 ar: {
 // Nav
 nav_home: 'الرئيسية',
 nav_about: 'من نحن',
 nav_activities: 'أنشطتنا',
 nav_why: 'لماذا نحن',
 nav_contact: 'تواصل معنا',

 // Top banner
 banner_group: 'مجموعة حداقة',
 banner_sub: 'مجموعة الخباز للمؤسسات',
 banner_location: 'الخبر، المنطقة الشرقية، المملكة العربية السعودية',
 banner_arabic: 'Al Khabbaz Corporate Enterprise',

 // Home Hero
 hero_tag: 'تأسست في الخبر، المملكة العربية السعودية',
 hero_title_1: 'التميز في الأعمال',
 hero_title_2: 'عبر',
 hero_title_span: 'أربعة محاور',
 hero_desc: 'مجموعة حداقة — مؤسسة متعددة الخدمات تقدم حلولاً في التجارة والإعلان والخط والطباعة للشركات في المنطقة الشرقية وما وراءها.',
 hero_btn_activities: 'استكشف أنشطتنا',
 hero_btn_contact: 'تواصل معنا',
 hero_stat_1_num: '٤',
 hero_stat_1_lbl: 'أنشطة تجارية',
 hero_stat_2_num: '٢٠+',
 hero_stat_2_lbl: 'سنوات خبرة',
 hero_stat_3_num: 'KSA',
 hero_stat_3_lbl: 'المملكة العربية السعودية',

 // Service mini cards — Arabic names from PDF
 svc_trading_title: 'حداقة للتجارة',
 svc_trading_desc: 'مستلزمات عامة، إلكترونيات، معدات السلامة والمكاتب',
 svc_advert_title: 'حداقة للدعاية والإعلان',
 svc_advert_desc: 'حملات تسويقية، تصميم ترويجي ووسائل إعلام',
 svc_calli_title: 'حداقة للخط والرسم',
 svc_calli_desc: 'خط عربي، لافتات وفنون الكتابة',
 svc_print_title: 'حداقة للطباعة',
 svc_print_desc: 'حلول الطباعة التجارية الأوفست والرقمية',

 // Strip
 strip_1_title: 'مجموعة الشركات',
 strip_1_desc: 'جزء من مجموعة الخباز للمؤسسات، تخدم المنطقة الشرقية',
 strip_2_title: 'الخبر، المملكة العربية السعودية',
 strip_2_desc: 'EKDB2729، ٢٧٢٩ الشارع الأول، الخبر الشمالية',
 strip_3_title: 'الحضور الإلكتروني',
 strip_3_desc: 'hadakah.com · alkhabbaz.net · hadakah-hpc.com.sa',
 strip_4_title: 'تواصل معنا',
 strip_4_desc: 'info@hadakah.com · info@alkhabbaz.net',

 // CTA
 cta_title: 'هل أنت مستعد للعمل معنا؟',
 cta_desc: 'تواصل معنا لمناقشة متطلباتك في التجارة أو الإعلان أو الخط أو الطباعة.',
 cta_enquiry: 'أرسل استفساراً',
 cta_learn: 'تعرف علينا',

 // About page
 page_about_tag: 'قصتنا',
 page_about_title: 'عن مجموعة حداقة',
 page_about_desc: 'مجموعة الخباز للمؤسسات — مبنية على الثقة والتميز والخبرة الإقليمية.',
 about_group_tag: 'عن المجموعة',
 about_h2: 'مجموعة الخباز للمؤسسات',
 about_p1: 'مجموعة الخباز للمؤسسات هي مجموعة أعمال متعددة التخصصات مقرها في الخبر، المنطقة الشرقية، المملكة العربية السعودية. تعمل تحت مظلة عائلة علامة حداقة التجارية، وتقدم المجموعة خدمات شاملة في مجالات التجارة والإعلان وفنون الخط العربي والطباعة التجارية.',
 about_p2: 'تمتد عملياتنا لتشمل التجارة العامة، وحلول تكنولوجيا المعلومات والإنترنت، والاستشارات الهندسية، والتشغيل والصيانة، وخدمات النظافة — مما يجعلنا شريكاً تجارياً متكاملاً للمؤسسات في جميع أنحاء المملكة.',
 pillar_1: 'توصيل موثوق',
 pillar_2: 'جودة مضمونة',
 pillar_3: 'خبرة محلية',
 pillar_4: 'فريق محترف',
 about_years: 'سنة من الخدمة',
 about_activities: 'أنشطة',
 mission_title: 'مهمتنا',
 mission_text: 'تقديم خدمات تجارية شاملة وعالية الجودة للشركات والمؤسسات في جميع أنحاء المملكة العربية السعودية، وتعزيز الشراكات طويلة الأمد المبنية على الثقة والاحترافية والنتائج.',
 vision_title: 'رؤيتنا',
 vision_text: 'أن نكون المؤسسة الرائدة متعددة الخدمات في المنطقة الشرقية، ونُعرف بالتميز في مجالات التجارة والإبداع والطباعة.',
 entities_tag: 'هيكل المجموعة',
 entities_title: 'كياناتنا التجارية',
 entity_1_name: 'مجموعة الخباز للمؤسسات',
 entity_1_desc: 'شركة القابضة الأم التي تشرف على جميع أنشطة مجموعة حداقة والشركات التابعة لها.',
 entity_2_name: 'مؤسسة حداقة للتجارة',
 entity_2_desc: 'التجارة العامة والمستلزمات والإلكترونيات ومعدات السلامة والمواد الصناعية.',
 entity_3_name: 'حداقة للنظافة ومكافحة الآفات',
 entity_3_desc: 'خدمات إدارة النظافة الاحترافية ومكافحة الآفات المتكاملة.',
 entity_4_name: 'الخباز للاستشارات الهندسية',
 entity_4_desc: 'الاستشارات الهندسية والتشغيل والصيانة والخدمات الاستشارية التقنية.',

 // Activities page — Arabic titles EXACTLY as in PDF
 page_act_tag: 'ما نقدمه',
 page_act_title: 'أنشطتنا الأربعة الرئيسية',
 page_act_desc: 'من التجارة والإعلان إلى الخط والطباعة — تقدم مجموعة حداقة خدمات احترافية في كل جانب من جوانب احتياجاتك التجارية.',
 act_1_label: 'النشاط الأول',
 act_1_title: 'حداقة للتجارة',
 act_1_desc: 'التجارة العامة في المجالات الصناعية والتجارية والمكتبية. نوفر منتجات عالية الجودة للشركات والمستشفيات والمصانع والجهات الحكومية في جميع أنحاء المملكة.',
 act_1_items: ['المعدات الكهربائية والإلكترونيات', 'معدات السلامة الصناعية', 'الملابس الموحدة الجاهزة', 'أجهزة الكمبيوتر والمحمول والإكسسوارات', 'أجهزة التصوير والاتصالات', 'المستلزمات العامة للمكاتب والمصانع والمستشفيات', 'الهدايا والمواد الترويجية'],
 act_1_link: 'عرض كتالوج المنتجات',
 act_2_label: 'النشاط الثاني',
 act_2_title: 'حداقة للدعاية والإعلان',
 act_2_desc: 'خدمات إعلانية وترويجية استراتيجية مصممة لرفع مستوى حضور علامتك التجارية في السوق السعودية. من تصميم الحملات إلى الإنتاج الإعلامي الكامل، نجعل رسالتك مسموعة.',
 act_2_items: ['تصميم العلامة التجارية والهوية البصرية', 'إنشاء الحملات الإعلانية', 'تصميم المواد الترويجية', 'تسويق الفعاليات واللافتات', 'إنتاج الوسائط الرقمية والمطبوعة', 'الاتصالات المؤسسية'],
 act_2_link: 'استكشف خدمات الإعلان',
 act_3_label: 'النشاط الثالث',
 act_3_title: 'حداقة للخط والرسم',
 act_3_desc: 'خدمات الخط العربي الاحترافية والرسم تجمع بين الفن التقليدي والتطبيقات التجارية الحديثة. مثالية للعلامات التجارية المؤسسية والديكور الداخلي والأماكن العامة.',
 act_3_items: ['أعمال الخط العربي الفني', 'اللافتات والإشارات المؤسسية', 'الكتابة الفنية للديكور الداخلي', 'لوحات الأسماء واللوحات المخصصة', 'الخطوط الفنية والزخرفية', 'لافتات المباني والمعالم'],
 act_3_link: 'معرض أعمال الخط والرسم',
 act_4_label: 'النشاط الرابع',
 act_4_title: 'حداقة للطباعة',
 act_4_desc: 'خدمات الطباعة التجارية والرقمية للشركات بجميع أحجامها. من مواد التسويق الصغيرة إلى الشاشات الكبيرة، نقدم دقة وجودة في كل مرة.',
 act_4_items: ['طباعة أوفست ورقمية', 'بطاقات العمل والكتيبات والنشرات', 'اللافتات والشاشات الكبيرة', 'القرطاسية والنماذج المؤسسية', 'طباعة التغليف والملصقات', 'الكتب والكتالوجات'],
 act_4_link: 'طلب عرض سعر للطباعة',

 // WhyUs page
 page_why_tag: 'لماذا حداقة',
 page_why_title: 'لماذا تشاركنا',
 page_why_desc: 'نجلب عقوداً من الخبرة الإقليمية وفريقاً محترفاً والتزاماً بتحقيق النتائج في جميع أنشطتنا التجارية.',
 feat_1_title: 'سجل حافل بالإنجازات',
 feat_1_desc: 'مع أكثر من ٢٠ عاماً في خدمة الشركات بالمنطقة الشرقية وما وراءها، تجلب مجموعة حداقة خبرة سوقية عميقة وسمعة موثوقة.',
 feat_2_title: 'قدرة متعددة الخدمات',
 feat_2_desc: 'من التوريد والإمداد إلى الإعلان الإبداعي والطباعة — أنشطتنا الأربعة المتكاملة تعني إمكانية تلبية جميع الاحتياجات التجارية تحت سقف واحد.',
 feat_3_title: 'معرفة بالسوق المحلي',
 feat_3_desc: 'مقرها في الخبر مع جذور راسخة في بيئة الأعمال السعودية، نفهم السوق الإقليمية والبيئة التنظيمية.',
 feat_4_title: 'خدمة سريعة الاستجابة',
 feat_4_desc: 'فريقنا ملتزم بالتواصل الفوري والاحترافي والتسليم في الوقت المحدد — لأن جداول أعمالكم تهمنا.',
 feat_5_title: 'التميز الإبداعي',
 feat_5_desc: 'يجمع فريق الخط والإعلان لدينا بين الإتقان الفني والفاعلية التجارية — لإنتاج أعمال تبرز حقاً.',
 feat_6_title: 'الثقة والنزاهة',
 feat_6_desc: 'نعمل بشفافية كاملة واحترافية. العلاقات طويلة الأمد مع عملائنا هي أساس طريقة عملنا.',
 val_tag: 'قيمنا',
 val_title: 'ما يحركنا',
 val_1_title: 'الجودة',
 val_1_desc: 'كل منتج وخدمة نقدمها تلتزم بأعلى معايير الجودة والاحترافية.',
 val_2_title: 'العلاقات',
 val_2_desc: 'نستثمر في الشراكات طويلة الأمد، ونتعامل مع كل عميل كمتعاون ذو قيمة.',
 val_3_title: 'الابتكار',
 val_3_desc: 'من الخط العربي التقليدي إلى الطباعة الرقمية الحديثة، نمزج بين الموروث والممارسة المعاصرة.',
 val_4_title: 'النزاهة',
 val_4_desc: 'تواصل شفاف، ومعاملات عادلة، والتزام بكلمتنا — دائماً.',

 // Contact page — ALL data from PDF in Arabic
 page_contact_tag: 'تواصل معنا',
 page_contact_title: 'تواصل مع مجموعة حداقة',
 page_contact_desc: 'نرحب باستفسارات الشركات والشركاء. تواصل معنا عبر أي من القنوات أدناه.',
 contact_phone_label: 'تلفونات',
 contact_phone_1: '٠٠٩٦٦٥٠٥٨٠٠٥٤٦',
 contact_phone_2: '٠٠٩٦٦٥٨١٥٩٢١٠٧',
 contact_phone_3: '٠٠٩٦٦٥٥٩٠١٦٧١٠',
 contact_email_label: 'البريد الإلكتروني',
 contact_email_1: 'info@hadakah.com',
 contact_email_2: 'info@alkhabbaz.net',
 contact_email_3: 'hdadvertising@gmail.com',
 contact_web_label: 'المواقع الإلكترونية',
 contact_addr_title: 'العنوان المسجل',
 contact_addr_code: 'EKDB2729',
 contact_addr_street: '٢٧٢٩ الشارع الأول',
 contact_addr_district: 'الخبر الشمالية – ٦٣٦٦-٣٤٤٢٩',
 contact_addr_city: 'الخبر، المنطقة الشرقية',
 contact_addr_country: 'المملكة العربية السعودية',
 form_title: 'أرسل لنا استفساراً',
 form_name: 'الاسم الكامل *',
 form_name_ph: 'اسمك الكامل',
 form_company: 'الشركة',
 form_company_ph: 'اسم شركتك',
 form_email: 'عنوان البريد الإلكتروني *',
 form_email_ph: 'your@email.com',
 form_phone: 'رقم الهاتف',
 form_phone_ph: '٠٠٩٦٦...',
 form_activity: 'النشاط المطلوب',
 form_act_default: '— اختر نشاطاً —',
 form_act_1: 'حداقة للتجارة (النشاط الأول)',
 form_act_2: 'حداقة للدعاية والإعلان (النشاط الثاني)',
 form_act_3: 'حداقة للخط والرسم (النشاط الثالث)',
 form_act_4: 'حداقة للطباعة (النشاط الرابع)',
 form_act_5: 'استفسار عام',
 form_msg: 'الرسالة *',
 form_msg_ph: 'أخبرنا عن متطلباتك...',
 form_submit: 'إرسال الاستفسار',
 form_note: 'نرد عادةً خلال ١–٢ يوم عمل.',
 form_success_title: 'شكراً على استفسارك!',
 form_success_desc: 'لقد استلمنا رسالتك وسنرد خلال ١–٢ يوم عمل.',
 form_another: 'إرسال استفسار آخر',

 // Footer
    // ── صفحات التفاصيل ──
    trading_section_tag: 'فئات المنتجات',
    trading_section_h2: 'ما نوفره',
    trading_cta_h2: 'طلب عرض سعر للتجارة',
    trading_cta_p: 'أخبرنا بما تحتاجه وسنوفره في أقرب وقت.',
    t_elec_title: 'المعدات الكهربائية والإلكترونيات',
    t_elec_desc: 'المعدات الكهربائية الصناعية والأجهزة الإلكترونية والكابلات ومعدات التوزيع وأجهزة الاتصالات.',
    t_safety_title: 'معدات السلامة الصناعية',
    t_safety_desc: 'معدات الوقاية الشخصية والخوذات وسترات السلامة ومعدات الحماية من الحرائق ولافتات السلامة.',
    t_uniform_title: 'الملابس الموحدة الجاهزة',
    t_uniform_desc: 'الزي الموحد للشركات وملابس العمل الصناعية والقمصان والسترات العاكسة والملابس المخصصة.',
    t_laptop_title: 'أجهزة الكمبيوتر والمحمول والإكسسوارات',
    t_laptop_desc: 'أجهزة المكتب والمحمول والطابعات والملحقات ومعدات الشبكات وأجهزة التصوير.',
    t_gifts_title: 'الهدايا والمواد الترويجية',
    t_gifts_desc: 'الهدايا المؤسسية والبضائع ذات العلامات التجارية والهدايا الترويجية والمواد المخصصة للفعاليات.',
    t_supply_title: 'المستلزمات العامة للمكاتب والصناعة',
    t_supply_desc: 'حلول تموين متكاملة للمكاتب والمستشفيات والمصانع والجهات الحكومية.',
    adv_section_tag: 'خدماتنا',
    adv_section_h2: 'خدمات الإعلان والترويج',
    adv_cta_h2: 'ابدأ حملتك الإعلانية',
    adv_cta_p: 'أخبرنا عن علامتك التجارية وأهدافك وسنضع استراتيجية تحقق نتائج.',
    a_brand_title: 'تصميم العلامة التجارية والهوية البصرية',
    a_brand_desc: 'تصميم الشعارات ولوحات الألوان والطباعة ودلائل العلامة التجارية وحزم الهوية البصرية الكاملة.',
    a_campaign_title: 'إنشاء الحملات الإعلانية',
    a_campaign_desc: 'استراتيجية حملة متكاملة ومفهوم إبداعي وكتابة المحتوى بالعربية والإنجليزية وتوزيع الإعلانات.',
    a_promo_title: 'تصميم المواد الترويجية',
    a_promo_desc: 'الكتيبات والنشرات والملصقات واللفافات وجميع المواد التسويقية المصممة باحترافية.',
    a_event_title: 'تسويق الفعاليات واللافتات',
    a_event_desc: 'الهوية البصرية للفعاليات وخلفيات المسارح وأجنحة المعارض والحزم البصرية الكاملة.',
    a_digital_title: 'إنتاج الوسائط الرقمية والمطبوعة',
    a_digital_desc: 'رسومات التواصل الاجتماعي والإعلانات الرقمية وحملات البريد الإلكتروني والحملات المتكاملة.',
    a_corp_title: 'الاتصالات المؤسسية',
    a_corp_desc: 'التقارير السنوية وملفات الشركة والعروض التقديمية وجميع الوثائق المؤسسية.',
    cal_section_tag: 'خدماتنا',
    cal_section_h2: 'خدمات الخط والرسم واللافتات',
    cal_cta_h2: 'طلب خط عربي مخصص',
    cal_cta_p: 'شاركنا رؤيتك وسيجسدها فنانونا باللغة العربية أو الإنجليزية.',
    c_calli_title: 'أعمال الخط العربي الفني',
    c_calli_desc: 'الخط العربي التقليدي والحديث للاستخدام المؤسسي والهدايا والأعمال الفنية المؤطرة والتركيبات الجدارية.',
    c_signs_title: 'اللافتات المؤسسية وأنظمة التوجيه',
    c_signs_desc: 'أنظمة لافتات خارجية وداخلية احترافية ولافتات اتجاهية وحلول التوجيه الكاملة.',
    c_interior_title: 'الكتابة الفنية للديكور الداخلي',
    c_interior_desc: 'حروف جدارية مخصصة واقتباسات ملهمة وطباعة زخرفية للمساحات الداخلية المؤسسية.',
    c_plaques_title: 'لوحات الأسماء واللوحات المخصصة',
    c_plaques_desc: 'لوحات الأسماء المنقوشة والمطبوعة ولوحات الجوائز واللوحات التذكارية الاحترافية.',
    c_deco_title: 'الخطوط الفنية والزخرفية',
    c_deco_desc: 'الخطوط العربية الزخرفية والفن الهندسي الإسلامي والأعمال الفنية المخصصة للفنادق والمساجد.',
    c_monument_title: 'لافتات المباني والمعالم',
    c_monument_desc: 'لافتات المعالم الخارجية الكبيرة وتعريف المباني والحروف المعمارية للمنشآت.',
    print_section_tag: 'خدمات الطباعة',
    print_section_h2: 'حلول الطباعة',
    print_quote_tag: 'احصل على سعر',
    print_quote_h2: 'طلب عرض سعر للطباعة',
    print_quote_p: 'أدخل التفاصيل أدناه وسنرسل لك عرض سعر تنافسي خلال 24 ساعة.',
    print_request_btn: 'طلب عرض سعر',
    print_success_h3: 'تم استلام طلب عرض السعر!',
    print_success_p: 'شكراً وسنرسل عرض سعر الطباعة خلال 24 ساعة.',
    print_submit_btn: 'إرسال طلب عرض السعر',
    print_qty_ph: 'مثال: 500 أو 1000 أو 5000',
    print_notes_ph: 'الحجم ونوع الورق والتشطيب وهل الأعمال الفنية جاهزة؟',
    print_type_lbl: 'نوع الطباعة *',
    print_qty_lbl: 'الكمية',
    print_notes_lbl: 'ملاحظات إضافية',
    print_opt_default: 'اختر النوع',
    print_opt_1: 'بطاقات العمل',
    print_opt_2: 'كتيبات ونشرات',
    print_opt_3: 'لافتات وشاشات عرض',
    print_opt_4: 'قرطاسية مؤسسية',
    print_opt_5: 'تغليف وملصقات',
    print_opt_6: 'كتب وكتالوجات',
    print_opt_7: 'أخرى',
    p_offset_title: 'طباعة أوفست ورقمية',
    p_offset_desc: 'طباعة أوفست تجارية عالية الحجم وطباعة رقمية بدقة ألوان استثنائية لأي كمية.',
    p_cards_title: 'بطاقات العمل والكتيبات والنشرات',
    p_cards_desc: 'بطاقات عمل فاخرة وكتيبات ثلاثية الطي ونشرات A5/A4 وجميع المواد التسويقية الصغيرة.',
    p_banner_title: 'اللافتات والشاشات الكبيرة',
    p_banner_desc: 'لافتات قابلة للسحب ولافتات فينيل ولوحات خارجية وشاشات معارض بأي حجم.',
    p_stationary_title: 'القرطاسية والنماذج المؤسسية',
    p_stationary_desc: 'الأوراق الرسمية والمظاريف ونماذج الفواتير ودفاتر الطلبات وحزم القرطاسية الكاملة.',
    p_packaging_title: 'طباعة التغليف والملصقات',
    p_packaging_desc: 'ملصقات المنتجات وطباعة الكراتين ولفات الملصقات وصناديق التغليف المخصصة.',
    p_books_title: 'الكتب والكتالوجات والمجلات',
    p_books_desc: 'الكتب المجلدة والكتالوجات وكتالوجات المنتجات والتقارير السنوية وإنتاج المجلات الكامل.',

 footer_desc: 'مؤسسة موثوقة متعددة الخدمات مقرها في الخبر، المملكة العربية السعودية — تقدم التميز في التجارة والإعلان والخط والطباعة.',
 footer_quick: 'روابط سريعة',
 footer_activities: 'الأنشطة',
 footer_contact: 'تواصل معنا',
 footer_copyright: '© ٢٠٢٥ مجموعة الخباز للمؤسسات / مجموعة حداقة. جميع الحقوق محفوظة · الخبر، المنطقة الشرقية، المملكة العربية السعودية.',
 }
}

export function LangProvider({ children }) {
 const [lang, setLang] = useState('en')
 const t = (key) => translations[lang][key] ?? translations['en'][key] ?? key
 return (
 <LangContext.Provider value={{ lang, setLang, t }}>
 {children}
 </LangContext.Provider>
 )
}

export function useLang() {
 return useContext(LangContext)
}
